const puzzleInput = [
{color:'muted lavender', holds: ['5 dull brown', '4 pale maroon', '2 drab orange']},
{color: 'plaid aqua', holds: ['1 posh violet', '5 pale yellow', '4 bright salmon']},
{color: 'wavy lime', holds: ['3 vibrant indigo', '1 posh gray']},
{color: 'pale coral', holds: ['5 mirrored olive', '2 posh salmon']},
{color: 'faded chartreuse', holds: ['1 plaid blue', '4 clear salmon', '5 muted teal']},
{color: 'vibrant indigo', holds: ['4 pale red', '1 vibrant violet']},
{color: 'vibrant salmon', holds: ['1 dull crimson', '5 dim coral', '4 pale salmon', '3 pale fuchsia']},
{color: 'light yellow', holds: ['5 clear beige', '3 dotted beige']},
{color: 'muted plum', holds: ['5 posh silver', '3 pale turquoise', '3 faded chartreuse']},
{color: 'mirrored indigo', holds: ['4 pale tan', '1 posh indigo', '3 shiny salmon', '4 wavy indigo']},
{color: 'pale indigo', holds: ['3 dark white']},
{color: 'plaid indigo', holds: ['4 mirrored teal']},
{color: 'shiny brown', holds: ['1 striped gold']},
{color: 'drab violet', holds: ['1 drab magenta', '5 posh orange', '1 mirrored brown', '4 wavy salmon']},
{color: 'pale olive', holds: ['2 light black', '2 faded tomato']},
{color: 'dark teal', holds: ['3 striped fuchsia']},
{color: 'plaid white', holds: ['4 shiny salmon']},
{color: 'muted gold', holds: ['5 faded lavender', '3 striped aqua']},
{color: 'pale cyan', holds: ['3 muted tan', '5 bright purple', '1 posh blue']},
{color: 'pale tan', holds: ['3 bright teal']},
{color: 'bright aqua', holds: ['5 plaid magenta', '5 muted lavender', '4 dim turquoise', '1 shiny turquoise']},
{color: 'dark gold', holds: ['4 dull indigo', '5 mirrored orange', '5 bright teal', '1 dim gold']},
{color: 'muted salmon', holds: ['3 muted gray', '4 pale salmon']},
{color: 'striped plum', holds: ['1 dark indigo', '1 vibrant violet']},
{color: 'posh yellow', holds: ['3 shiny tan', '4 dull lavender', '5 pale yellow']},
{color: 'plaid lime', holds: ['2 bright brown', '4 dull lavender']},
{color: 'mirrored gray', holds: ['4 mirrored teal', '3 muted indigo']},
{color: 'muted olive', holds: ['3 dim fuchsia', '2 dim salmon', '4 shiny maroon']},
{color: 'dotted blue', holds: ['4 plaid orange', '5 faded black', '2 muted black', '5 mirrored lime']},
{color: 'wavy beige', holds: ['5 dark aqua', '3 mirrored lavender', '3 drab fuchsia']},
{color: 'shiny indigo', holds: ['3 wavy black', '2 dull plum']},
{color: 'drab lavender', holds: ['4 mirrored chartreuse']},
{color: 'vibrant tomato', holds: ['3 wavy white', '1 dull plum']},
{color: 'plaid teal', holds: ['3 mirrored bronze']},
{color: 'pale chartreuse', holds: []},
{color: 'muted coral', holds: ['1 striped lavender', '5 dotted crimson', '2 faded tomato']},
{color: 'faded aqua', holds: ['2 bright plum', '3 faded gold', '1 mirrored bronze', '2 dull lavender']},
{color: 'pale brown', holds: ['1 clear salmon', '4 drab tan', '1 light orange', '1 light silver']},
{color: 'drab orange', holds: ['3 faded beige']},
{color: 'pale blue', holds: ['3 pale plum', '3 dotted green', '4 dark lime', '5 clear beige']},
{color: 'dull purple', holds: ['5 posh aqua', '1 muted blue', '1 bright gray', '1 muted chartreuse']},
{color: 'bright silver', holds: ['5 dark turquoise', '2 dark teal', '1 muted tan', '3 vibrant tan']},
{color: 'dim silver', holds: ['4 plaid black']},
{color: 'faded violet', holds: ['5 dark maroon']},
{color: 'pale maroon', holds: ['5 dark maroon', '4 drab chartreuse']},
{color: 'shiny green', holds: ['1 bright chartreuse']},
{color: 'vibrant crimson', holds: ['3 dotted red', '2 striped violet', '1 light bronze']},
{color: 'clear lavender', holds: ['1 faded teal', '5 clear cyan']},
{color: 'mirrored red', holds: ['2 dim gray', '2 drab orange', '4 muted purple', '3 muted white']},
{color: 'striped green', holds: ['2 light purple', '4 light gold', '3 posh magenta']},
{color: 'dim yellow', holds: ['1 light crimson', '2 muted indigo']},
{color: 'dotted orange', holds: ['3 wavy salmon', '1 dim fuchsia']},
{color: 'vibrant gray', holds: ['1 plaid brown', '5 mirrored black', '4 plaid olive']},
{color: 'mirrored silver', holds: ['2 striped magenta', '3 striped coral']},
{color: 'pale magenta', holds: ['4 posh tomato', '4 plaid blue', '2 shiny gold', '3 faded beige']},
{color: 'vibrant black', holds: ['4 dotted brown']},
{color: 'muted violet', holds: ['1 clear tomato', '1 striped beige']},
{color: 'clear salmon', holds: ['1 drab chartreuse', '4 dotted beige', '5 light crimson', '3 dotted orange']},
{color: 'posh indigo', holds: ['3 mirrored teal', '5 drab gold']},
{color: 'wavy black', holds: ['5 dotted purple', '5 plaid chartreuse', '3 striped gold']},
{color: 'mirrored lavender', holds: ['2 dim black']},
{color: 'shiny maroon', holds: ['2 dotted beige']},
{color: 'drab magenta', holds: ['2 dim yellow']},
{color: 'pale orange', holds: ['1 shiny purple', '5 striped turquoise', '2 light crimson']},
{color: 'shiny beige', holds: ['5 clear white', '2 striped turquoise', '4 pale yellow', '1 muted black']},
{color: 'striped cyan', holds: ['2 plaid yellow', '2 clear teal', '3 wavy olive', '4 posh violet']},
{color: 'dull cyan', holds: ['1 striped salmon']},
{color: 'vibrant green', holds: ['4 dull coral', '4 drab yellow', '4 dark cyan']},
{color: 'wavy cyan', holds: ['5 light salmon', '5 dim blue', '2 pale green', '1 faded indigo']},
{color: 'drab plum', holds: ['3 dark magenta']},
{color: 'light aqua', holds: ['4 bright bronze', '3 wavy lavender', '3 dull cyan', '2 bright green']},
{color: 'pale plum', holds: ['5 clear plum']},
{color: 'vibrant silver', holds: ['1 dim lavender', '4 bright teal']},
{color: 'wavy white', holds: ['1 light crimson', '4 wavy salmon']},
{color: 'shiny chartreuse', holds: ['2 plaid gray', '5 mirrored white']},
{color: 'dull chartreuse', holds: ['1 dull cyan', '3 striped white', '4 posh indigo']},
{color: 'clear magenta', holds: ['1 plaid coral', '5 light plum', '1 bright yellow']},
{color: 'muted white', holds: ['2 dull salmon', '5 bright turquoise', '3 wavy gray', '1 plaid black']},
{color: 'dull brown', holds: ['3 faded lavender']},
{color: 'muted turquoise', holds: ['4 mirrored plum', '4 mirrored brown', '4 drab salmon', '4 mirrored tomato']},
{color: 'posh tomato', holds: ['2 drab orange', '4 dim lavender']},
{color: 'shiny fuchsia', holds: ['3 dull black', '5 wavy coral']},
{color: 'dim gray', holds: ['3 drab gray']},
{color: 'striped olive', holds: ['5 light purple', '5 wavy yellow', '1 striped fuchsia']},
{color: 'muted maroon', holds: ['2 bright white']},
{color: 'light tomato', holds: ['1 striped indigo', '5 plaid plum', '4 clear indigo', '4 drab tan']},
{color: 'plaid violet', holds: ['2 dim coral']},
{color: 'striped chartreuse', holds: ['2 shiny gray']},
{color: 'mirrored white', holds: ['4 striped beige']},
{color: 'dim beige', holds: ['3 wavy bronze', '4 vibrant silver', '1 striped white', '2 dark plum']},
{color: 'striped violet', holds: ['5 dull teal', '2 vibrant red']},
{color: 'drab green', holds: ['1 striped olive', '2 light salmon', '1 faded cyan', '3 vibrant fuchsia']},
{color: 'clear lime', holds: ['2 plaid coral', '1 light lavender', '4 posh salmon']},
{color: 'striped indigo', holds: ['2 pale maroon', '5 dotted aqua', '3 drab gray']},
{color: 'dim blue', holds: ['5 faded bronze', '4 dark blue']},
{color: 'faded fuchsia', holds: ['3 muted fuchsia', '1 light orange', '2 striped beige', '1 dotted red']},
{color: 'plaid red', holds: ['5 pale maroon', '3 dark beige', '2 striped fuchsia']},
{color: 'drab silver', holds: ['1 dim salmon', '2 shiny salmon']},
{color: 'dark chartreuse', holds: ['1 dull aqua']},
{color: 'clear chartreuse', holds: ['5 faded brown', '3 dotted aqua']},
{color: 'plaid silver', holds: ['5 pale red']},
{color: 'wavy chartreuse', holds: ['5 mirrored red', '1 dull teal']},
{color: 'clear gray', holds: ['5 striped salmon', '5 plaid silver', '1 clear black']},
{color: 'shiny white', holds: ['1 shiny gray', '5 vibrant gray']},
{color: 'posh coral', holds: ['2 muted white']},
{color: 'light red', holds: ['5 muted indigo', '1 wavy fuchsia']},
{color: 'dull fuchsia', holds: ['4 light plum', '4 faded red']},
{color: 'dotted gold', holds: ['1 plaid brown', '4 dotted aqua', '2 pale purple']},
{color: 'faded orange', holds: ['3 dotted beige']},
{color: 'bright coral', holds: ['2 dark cyan', '1 wavy tan', '1 vibrant yellow']},
{color: 'striped brown', holds: ['5 light yellow', '4 dull indigo', '4 clear maroon']},
{color: 'light fuchsia', holds: ['3 dotted gray', '1 striped orange', '1 mirrored olive', '2 wavy fuchsia']},
{color: 'dotted bronze', holds: ['2 dull salmon']},
{color: 'faded red', holds: ['2 posh indigo', '5 dotted aqua']},
{color: 'wavy teal', holds: ['3 faded tomato', '4 dark silver', '3 shiny cyan']},
{color: 'dim tomato', holds: ['4 wavy silver', '3 drab red']},
{color: 'muted beige', holds: ['1 bright gray', '1 dark red']},
{color: 'shiny yellow', holds: ['2 light plum']},
{color: 'wavy indigo', holds: ['1 faded red', '1 plaid yellow', '2 dull aqua']},
{color: 'plaid maroon', holds: ['5 vibrant beige']},
{color: 'wavy tan', holds: ['5 plaid maroon']},
{color: 'striped coral', holds: ['1 pale silver', '4 clear beige', '3 dotted aqua', '3 striped turquoise']},
{color: 'shiny black', holds: ['1 clear silver', '1 mirrored blue']},
{color: 'muted silver', holds: ['1 posh teal', '4 faded teal', '4 plaid aqua', '2 striped olive']},
{color: 'pale gray', holds: ['4 dotted silver']},
{color: 'light white', holds: ['2 dull salmon', '5 vibrant violet', '1 dull black']},
{color: 'mirrored beige', holds: ['3 dark teal', '3 wavy coral', '3 plaid black']},
{color: 'mirrored tomato', holds: ['5 muted bronze', '2 drab gold', '4 dark plum']},
{color: 'dull magenta', holds: ['1 wavy black', '5 dull gray']},
{color: 'pale crimson', holds: ['3 wavy brown', '5 dark green', '3 pale fuchsia']},
{color: 'pale beige', holds: ['3 posh black', '4 dotted gold', '1 plaid blue']},
{color: 'dull red', holds: ['2 light chartreuse', '1 striped tomato', '4 plaid green', '3 dull chartreuse']},
{color: 'dotted violet', holds: ['4 dark plum', '3 dull plum', '4 pale red']},
{color: 'muted bronze', holds: ['2 muted teal', '5 shiny purple', '4 pale chartreuse', '4 wavy salmon']},
{color: 'dark coral', holds: ['5 dull indigo', '1 vibrant plum', '2 mirrored black', '4 drab gold']},
{color: 'shiny magenta', holds: ['5 light turquoise', '4 striped olive']},
{color: 'faded olive', holds: ['2 clear white']},
{color: 'pale aqua', holds: ['2 vibrant fuchsia']},
{color: 'vibrant yellow', holds: ['4 muted teal', '1 mirrored teal']},
{color: 'dotted lime', holds: ['5 dotted white', '2 wavy aqua', '3 pale salmon']},
{color: 'dark bronze', holds: ['1 clear beige', '1 muted olive']},
{color: 'dim lavender', holds: ['1 dull indigo', '2 shiny purple', '4 dull teal']},
{color: 'wavy gold', holds: ['5 dull black', '1 muted fuchsia', '4 dark red', '1 light crimson']},
{color: 'striped crimson', holds: ['5 shiny gray', '3 mirrored crimson', '2 drab chartreuse', '4 dull aqua']},
{color: 'dark aqua', holds: ['1 bright indigo', '5 muted white', '2 shiny crimson', '3 mirrored orange']},
{color: 'posh black', holds: ['3 pale tan', '1 dim brown', '5 clear green']},
{color: 'bright beige', holds: ['4 dotted black']},
{color: 'dull maroon', holds: ['1 drab red', '4 faded turquoise', '1 pale olive']},
{color: 'dull salmon', holds: ['3 mirrored olive', '3 dull indigo', '1 dim brown', '4 shiny lime']},
{color: 'faded purple', holds: ['4 faded indigo']},
{color: 'light beige', holds: ['1 posh gray', '3 dotted white', '1 striped silver']},
{color: 'vibrant magenta', holds: ['4 drab red', '1 dotted white', '5 striped aqua']},
{color: 'light maroon', holds: ['1 dull black']},
{color: 'light olive', holds: ['3 dull tan']},
{color: 'vibrant lime', holds: ['2 dim lavender']},
{color: 'muted aqua', holds: ['3 bright olive', '1 muted teal', '3 dull crimson']},
{color: 'dotted beige', holds: []},
{color: 'dotted indigo', holds: ['2 light lavender', '5 dark white', '3 wavy gray', '4 plaid chartreuse']},
{color: 'drab yellow', holds: ['4 mirrored aqua', '5 plaid olive', '5 dull black', '4 striped turquoise']},
{color: 'light lime', holds: ['3 striped turquoise', '4 muted coral', '5 muted yellow', '4 mirrored silver']},
{color: 'dark crimson', holds: ['2 light bronze', '1 vibrant chartreuse']},
{color: 'clear plum', holds: ['1 muted indigo', '5 dim red', '2 pale orange', '5 light black']},
{color: 'mirrored violet', holds: ['3 wavy salmon']},
{color: 'striped silver', holds: ['5 bright olive', '5 dim brown', '2 posh blue', '1 posh purple']},
{color: 'posh gold', holds: ['5 faded lavender']},
{color: 'striped lime', holds: ['4 striped coral']},
{color: 'plaid tomato', holds: ['2 dull white', '1 wavy white', '5 drab red']},
{color: 'drab tan', holds: ['1 mirrored bronze', '1 mirrored tomato', '2 mirrored green']},
{color: 'posh purple', holds: ['4 dull cyan']},
{color: 'plaid blue', holds: ['2 muted fuchsia', '1 bright teal', '2 pale chartreuse']},
{color: 'dim lime', holds: ['4 drab gold', '1 muted fuchsia', '1 posh tomato']},
{color: 'dark white', holds: ['2 wavy gold']},
{color: 'bright red', holds: ['4 light fuchsia', '1 plaid orange', '1 pale red']},
{color: 'wavy blue', holds: ['4 striped red', '1 mirrored black']},
{color: 'light teal', holds: ['1 faded orange', '5 muted white']},
{color: 'shiny blue', holds: ['1 drab red', '3 shiny brown', '2 dark teal', '2 dotted silver']},
{color: 'bright gray', holds: ['3 muted teal', '2 clear plum', '5 light olive', '5 dark red']},
{color: 'bright black', holds: ['5 posh yellow', '1 striped maroon']},
{color: 'shiny gold', holds: ['3 wavy gold', '2 plaid chartreuse', '2 shiny lime', '5 dull indigo']},
{color: 'striped teal', holds: ['4 dark lime', '4 light yellow', '2 dull brown']},
{color: 'wavy coral', holds: ['3 dim yellow', '1 clear red', '4 pale chartreuse']},
{color: 'plaid chartreuse', holds: ['1 striped maroon', '5 dotted yellow']},
{color: 'pale turquoise', holds: ['3 clear yellow', '2 dim coral']},
{color: 'vibrant plum', holds: ['3 dotted yellow']},
{color: 'drab cyan', holds: ['5 vibrant green']},
{color: 'wavy crimson', holds: ['1 mirrored gray', '2 dim teal']},
{color: 'wavy maroon', holds: ['3 pale tan']},
{color: 'light orange', holds: ['4 vibrant silver', '2 dim olive', '2 drab red']},
{color: 'plaid brown', holds: ['2 bright turquoise', '4 shiny tan', '2 dull indigo', '3 plaid olive']},
{color: 'posh silver', holds: ['5 wavy coral']},
{color: 'wavy bronze', holds: ['1 plaid yellow', '1 dim gold']},
{color: 'shiny violet', holds: ['5 plaid coral', '2 mirrored brown']},
{color: 'posh lime', holds: ['3 wavy bronze', '2 striped tomato', '2 pale tan']},
{color: 'dim salmon', holds: ['3 dim brown', '5 drab chartreuse']},
{color: 'faded beige', holds: []},
{color: 'dotted gray', holds: ['5 dark lime', '2 posh black', '3 muted fuchsia']},
{color: 'dull crimson', holds: ['5 vibrant fuchsia']},
{color: 'drab brown', holds: ['5 pale maroon', '5 light crimson']},
{color: 'bright blue', holds: ['5 vibrant brown']},
{color: 'bright violet', holds: ['1 light white', '5 clear beige', '2 dull crimson']},
{color: 'plaid magenta', holds: ['2 light plum', '1 wavy white', '5 pale green', '1 bright tomato']},
{color: 'faded silver', holds: ['5 light black', '5 mirrored teal', '5 vibrant plum']},
{color: 'wavy brown', holds: ['4 faded gray', '3 dotted olive', '1 light silver']},
{color: 'clear teal', holds: ['2 mirrored black', '2 wavy gold', '2 striped red', '5 light silver']},
{color: 'posh crimson', holds: ['5 drab tan']},
{color: 'clear fuchsia', holds: ['4 faded tomato', '1 dotted beige']},
{color: 'bright maroon', holds: ['2 wavy teal', '2 shiny gray', '5 dull gray', '3 dull teal']},
{color: 'drab gray', holds: ['3 dark white', '2 pale salmon', '4 bright teal']},
{color: 'vibrant brown', holds: ['4 wavy salmon']},
{color: 'bright green', holds: ['2 clear cyan', '3 wavy lavender', '2 plaid blue', '2 faded gold']},
{color: 'light salmon', holds: ['1 muted tan', '5 plaid plum']},
{color: 'plaid bronze', holds: ['4 mirrored chartreuse', '3 plaid turquoise', '2 wavy orange', '5 dotted yellow']},
{color: 'dull bronze', holds: ['2 vibrant lime', '2 muted purple', '2 dark magenta']},
{color: 'bright orange', holds: ['4 pale violet', '2 light fuchsia', '3 dull purple']},
{color: 'wavy fuchsia', holds: ['4 dotted olive', '1 dull brown']},
{color: 'mirrored olive', holds: ['4 muted fuchsia', '4 striped turquoise']},
{color: 'shiny salmon', holds: ['2 dark white']},
{color: 'striped tan', holds: ['4 mirrored purple']},
{color: 'dull coral', holds: ['3 posh coral', '1 dotted green']},
{color: 'drab teal', holds: ['4 wavy yellow', '5 mirrored aqua']},
{color: 'shiny tan', holds: ['5 striped maroon', '5 vibrant red']},
{color: 'bright crimson', holds: ['1 muted magenta']},
{color: 'shiny lime', holds: ['1 faded teal', '1 light crimson']},
{color: 'posh white', holds: ['3 posh orange', '4 pale gray', '5 dull maroon', '5 plaid plum']},
{color: 'dotted brown', holds: ['1 vibrant indigo', '1 plaid olive']},
{color: 'faded coral', holds: ['5 muted bronze', '3 mirrored lavender']},
{color: 'faded brown', holds: ['1 bright turquoise', '3 posh indigo', '2 pale fuchsia', '3 dark indigo']},
{color: 'vibrant aqua', holds: ['2 clear beige', '3 posh olive', '3 dark turquoise', '2 posh magenta']},
{color: 'dark turquoise', holds: ['1 striped gold', '1 mirrored red']},
{color: 'drab gold', holds: ['2 clear beige', '4 striped turquoise', '1 pale orange', '1 clear salmon']},
{color: 'mirrored green', holds: ['4 dotted beige', '3 pale chartreuse', '3 light crimson']},
{color: 'clear violet', holds: ['3 posh orange', '4 faded beige', '3 drab red', '4 shiny salmon']},
{color: 'posh plum', holds: ['1 shiny white', '1 striped lavender']},
{color: 'vibrant purple', holds: ['5 bright teal']},
{color: 'dark salmon', holds: ['4 striped olive', '5 mirrored crimson', '5 plaid lime', '3 dark tomato']},
{color: 'shiny silver', holds: ['2 vibrant red']},
{color: 'dull turquoise', holds: ['3 faded crimson', '1 drab maroon', '5 drab gold']},
{color: 'dull orange', holds: ['1 dark yellow', '3 bright beige']},
{color: 'bright bronze', holds: ['3 posh salmon', '1 mirrored violet', '2 muted white', '3 dotted orange']},
{color: 'bright teal', holds: ['4 dim fuchsia']},
{color: 'clear turquoise', holds: ['1 faded teal', '2 dull teal']},
{color: 'wavy magenta', holds: ['4 dim teal', '3 mirrored bronze', '3 plaid plum', '5 wavy lavender']},
{color: 'faded bronze', holds: ['2 striped salmon', '3 dark red', '1 dark indigo']},
{color: 'faded plum', holds: ['1 clear green']},
{color: 'faded maroon', holds: ['1 striped maroon', '5 dim black', '1 vibrant indigo']},
{color: 'muted teal', holds: ['4 light crimson', '5 drab chartreuse']},
{color: 'vibrant maroon', holds: ['3 dark fuchsia', '3 plaid turquoise', '1 pale silver', '4 shiny cyan']},
{color: 'plaid crimson', holds: ['3 mirrored olive']},
{color: 'clear tan', holds: ['1 vibrant purple', '1 wavy aqua']},
{color: 'clear aqua', holds: ['4 bright white']},
{color: 'striped red', holds: ['3 wavy coral', '3 dark white', '4 muted fuchsia', '4 posh tomato']},
{color: 'posh violet', holds: ['1 muted fuchsia', '3 dim coral', '2 drab orange']},
{color: 'plaid cyan', holds: ['2 shiny indigo']},
{color: 'light chartreuse', holds: ['5 wavy tan', '4 clear indigo']},
{color: 'vibrant lavender', holds: ['3 light gray', '4 striped beige', '5 dark maroon', '3 drab fuchsia']},
{color: 'dim red', holds: ['4 pale orange', '3 drab chartreuse']},
{color: 'vibrant turquoise', holds: ['3 clear tomato', '4 posh blue']},
{color: 'muted green', holds: ['4 clear bronze', '3 dotted black', '3 dull beige']},
{color: 'faded salmon', holds: ['2 drab gold', '2 clear red', '2 dark indigo', '5 plaid teal']},
{color: 'posh chartreuse', holds: ['4 dotted orange']},
{color: 'dotted turquoise', holds: ['5 shiny fuchsia', '2 vibrant indigo', '3 vibrant fuchsia', '5 muted green']},
{color: 'wavy turquoise', holds: ['1 dark white', '4 posh tan']},
{color: 'clear purple', holds: ['2 vibrant gray', '3 dark plum', '1 shiny fuchsia', '4 plaid indigo']},
{color: 'pale tomato', holds: ['2 striped silver', '1 mirrored aqua']},
{color: 'pale salmon', holds: ['4 muted indigo', '4 faded teal']},
{color: 'dark maroon', holds: ['5 dotted orange', '5 faded beige', '3 wavy salmon', '5 dim lavender']},
{color: 'faded green', holds: ['3 wavy coral', '5 dull indigo', '4 dim salmon', '1 pale gray']},
{color: 'bright gold', holds: ['4 drab lavender']},
{color: 'dull white', holds: ['4 clear salmon', '2 shiny gold']},
{color: 'drab olive', holds: ['3 pale lime', '3 striped crimson', '5 plaid gray', '2 posh magenta']},
{color: 'bright cyan', holds: ['4 dotted black']},
{color: 'drab beige', holds: ['4 shiny yellow']},
{color: 'dotted salmon', holds: ['5 light maroon', '5 dotted gray']},
{color: 'posh gray', holds: ['3 dark red', '2 mirrored gray', '2 dim brown', '4 dotted aqua']},
{color: 'dull gray', holds: ['2 shiny beige', '5 posh silver']},
{color: 'light blue', holds: ['1 dim coral', '5 vibrant plum', '1 clear salmon', '1 clear yellow']},
{color: 'striped gray', holds: ['5 striped indigo', '1 faded lime', '2 light tomato']},
{color: 'dark violet', holds: ['1 posh gray', '5 shiny cyan', '2 pale indigo', '4 light coral']},
{color: 'striped black', holds: ['5 dotted maroon', '1 drab blue']},
{color: 'shiny coral', holds: ['1 clear yellow', '5 striped plum', '4 dull tomato']},
{color: 'faded tan', holds: ['5 vibrant bronze', '5 muted fuchsia', '1 pale coral', '4 dull indigo']},
{color: 'pale white', holds: ['4 clear cyan', '2 bright yellow', '4 vibrant tomato']},
{color: 'plaid plum', holds: ['5 pale violet', '3 posh yellow', '3 faded silver']},
{color: 'bright fuchsia', holds: ['5 clear black']},
{color: 'dotted red', holds: ['3 dark magenta', '5 clear indigo', '1 faded bronze', '4 dotted gray']},
{color: 'plaid turquoise', holds: ['2 dark indigo']},
{color: 'pale lavender', holds: ['4 posh fuchsia', '1 clear black', '4 wavy lime']},
{color: 'bright lavender', holds: ['2 wavy magenta', '5 plaid blue', '1 drab yellow', '1 muted gray']},
{color: 'bright white', holds: ['4 light gray']},
{color: 'dull black', holds: ['2 shiny lime', '3 muted indigo', '5 faded beige']},
{color: 'muted tomato', holds: ['2 dark yellow']},
{color: 'plaid fuchsia', holds: ['2 dull lavender']},
{color: 'dark indigo', holds: ['2 dim lavender', '3 shiny maroon']},
{color: 'mirrored magenta', holds: ['1 mirrored chartreuse']},
{color: 'vibrant violet', holds: ['5 dotted beige', '5 plaid olive']},
{color: 'pale lime', holds: ['1 vibrant silver', '4 shiny white', '2 wavy orange', '3 plaid coral']},
{color: 'mirrored aqua', holds: ['5 light yellow', '3 plaid silver', '2 dark white', '2 dull teal']},
{color: 'striped turquoise', holds: ['1 bright turquoise', '2 faded beige']},
{color: 'faded indigo', holds: ['2 dotted purple']},
{color: 'plaid green', holds: ['3 dim orange']},
{color: 'dotted lavender', holds: ['5 dotted crimson', '5 bright turquoise', '3 muted lavender', '4 mirrored olive']},
{color: 'muted tan', holds: ['2 faded orange', '5 mirrored gray', '1 faded green']},
{color: 'dark plum', holds: ['2 mirrored olive', '4 muted fuchsia', '2 shiny maroon', '1 dim fuchsia']},
{color: 'light cyan', holds: ['4 dotted gray', '4 wavy red', '1 dull white']},
{color: 'striped gold', holds: ['2 wavy silver', '2 muted purple', '3 wavy coral']},
{color: 'striped white', holds: ['4 wavy coral', '4 pale plum', '2 wavy black', '5 dim olive']},
{color: 'mirrored yellow', holds: ['3 plaid chartreuse', '4 muted gold', '1 mirrored bronze']},
{color: 'clear tomato', holds: ['3 striped indigo', '3 dim fuchsia', '2 wavy gray']},
{color: 'faded teal', holds: []},
{color: 'faded lavender', holds: ['2 clear bronze', '3 muted teal', '2 dotted yellow', '5 shiny purple']},
{color: 'posh lavender', holds: ['5 posh gray']},
{color: 'bright brown', holds: ['2 dull crimson', '5 muted bronze', '4 dark indigo', '5 mirrored orange']},
{color: 'faded crimson', holds: ['3 dotted crimson']},
{color: 'mirrored teal', holds: ['1 plaid blue', '1 clear red', '5 striped turquoise', '4 dotted beige']},
{color: 'dark fuchsia', holds: ['1 faded green']},
{color: 'dim coral', holds: ['5 clear salmon', '4 dotted beige', '1 pale salmon', '2 plaid chartreuse']},
{color: 'posh blue', holds: ['3 pale maroon', '5 dim coral']},
{color: 'light indigo', holds: ['1 vibrant silver', '1 bright chartreuse', '1 light black']},
{color: 'shiny lavender', holds: ['4 dotted olive', '5 faded brown', '1 plaid tomato']},
{color: 'dotted white', holds: ['4 dim olive']},
{color: 'dotted chartreuse', holds: ['4 striped turquoise', '1 dotted silver']},
{color: 'faded black', holds: ['2 muted white', '3 drab teal', '3 wavy gray']},
{color: 'vibrant white', holds: ['4 dark white', '4 clear violet', '3 plaid magenta', '5 dark green']},
{color: 'faded magenta', holds: ['3 faded green', '4 plaid olive', '5 plaid brown', '1 wavy salmon']},
{color: 'dull plum', holds: ['3 muted purple']},
{color: 'dim indigo', holds: ['5 dotted fuchsia', '5 drab red', '1 dull green', '5 dim fuchsia']},
{color: 'pale yellow', holds: ['4 mirrored bronze']},
{color: 'light violet', holds: ['5 dull black']},
{color: 'posh green', holds: ['1 plaid plum', '3 pale violet', '5 muted salmon']},
{color: 'mirrored purple', holds: ['3 mirrored aqua', '1 plaid blue']},
{color: 'clear orange', holds: ['3 light beige']},
{color: 'striped tomato', holds: ['4 dark orange', '1 bright aqua']},
{color: 'dark gray', holds: ['1 posh violet']},
{color: 'plaid beige', holds: ['5 pale beige']},
{color: 'plaid gray', holds: ['3 mirrored bronze', '3 clear green', '5 dark chartreuse']},
{color: 'mirrored coral', holds: ['1 pale tan', '2 plaid coral', '5 striped bronze']},
{color: 'dull silver', holds: ['1 vibrant purple', '3 drab lavender', '2 mirrored salmon']},
{color: 'clear yellow', holds: ['1 shiny gold', '4 dotted beige', '4 dark lime']},
{color: 'light gold', holds: ['3 shiny white', '4 dim violet', '1 light olive']},
{color: 'drab white', holds: ['5 shiny lavender', '4 dotted lavender']},
{color: 'faded yellow', holds: ['2 dull crimson', '3 muted indigo', '2 plaid crimson', '3 clear green']},
{color: 'light gray', holds: ['2 plaid orange', '5 plaid lavender']},
{color: 'dim bronze', holds: ['1 vibrant coral', '1 wavy teal', '1 pale crimson']},
{color: 'shiny gray', holds: ['5 light lavender', '3 drab red', '1 plaid chartreuse']},
{color: 'striped beige', holds: ['3 light black', '1 dull teal']},
{color: 'dotted fuchsia', holds: ['3 faded indigo', '2 dim gray']},
{color: 'plaid yellow', holds: ['4 pale maroon', '5 dull black', '1 plaid chartreuse', '3 drab orange']},
{color: 'muted orange', holds: ['3 muted lavender']},
{color: 'muted crimson', holds: ['4 muted cyan', '1 dull plum']},
{color: 'muted red', holds: ['5 faded turquoise', '5 light silver', '5 dotted aqua']},
{color: 'vibrant chartreuse', holds: ['4 wavy violet', '1 plaid beige', '2 clear cyan', '2 dull lavender']},
{color: 'pale fuchsia', holds: ['3 plaid blue', '3 muted bronze', '4 faded blue']},
{color: 'dotted tomato', holds: ['4 dark tomato', '3 plaid orange', '5 posh teal']},
{color: 'dim green', holds: ['1 dull white']},
{color: 'dim aqua', holds: ['2 light silver', '3 faded silver', '3 dotted orange', '4 vibrant salmon']},
{color: 'dim brown', holds: []},
{color: 'muted chartreuse', holds: ['2 dark coral', '5 striped plum']},
{color: 'drab indigo', holds: ['2 posh brown']},
{color: 'dark orange', holds: ['4 plaid blue', '1 dark brown', '2 striped indigo', '1 dark magenta']},
{color: 'bright yellow', holds: ['3 clear tomato']},
{color: 'clear bronze', holds: ['4 wavy salmon']},
{color: 'dotted olive', holds: ['4 striped beige', '3 drab orange', '3 bright teal']},
{color: 'dull violet', holds: ['4 plaid salmon', '5 faded olive']},
{color: 'clear white', holds: ['2 plaid coral', '1 muted indigo', '1 striped beige']},
{color: 'dull tan', holds: ['5 dim red', '5 posh gold', '2 clear red']},
{color: 'mirrored plum', holds: ['4 dim beige']},
{color: 'wavy purple', holds: ['2 posh silver', '5 shiny tan', '3 pale red', '3 dull salmon']},
{color: 'dim black', holds: ['3 light yellow']},
{color: 'dotted coral', holds: ['3 pale violet']},
{color: 'posh bronze', holds: ['1 posh tomato', '1 drab purple', '3 dim fuchsia', '2 bright brown']},
{color: 'wavy salmon', holds: []},
{color: 'dull blue', holds: ['5 dark plum', '4 light yellow']},
{color: 'faded lime', holds: ['2 dim red', '3 drab lavender', '5 muted black', '2 light coral']},
{color: 'vibrant coral', holds: ['4 muted purple', '5 pale chartreuse', '5 dotted black']},
{color: 'mirrored chartreuse', holds: ['5 muted olive']},
{color: 'dark lime', holds: ['1 dark magenta']},
{color: 'light coral', holds: ['2 dull lavender']},
{color: 'bright lime', holds: ['2 wavy bronze']},
{color: 'mirrored orange', holds: ['1 pale salmon', '1 light orange']},
{color: 'muted brown', holds: ['3 clear beige', '1 faded salmon', '2 vibrant cyan', '4 clear white']},
{color: 'posh orange', holds: ['2 dark lime', '3 wavy purple']},
{color: 'posh magenta', holds: ['2 dark teal']},
{color: 'drab salmon', holds: ['5 drab tomato']},
{color: 'muted fuchsia', holds: []},
{color: 'wavy tomato', holds: ['4 wavy black', '4 faded teal']},
{color: 'dim chartreuse', holds: ['5 drab green', '4 drab magenta']},
{color: 'dotted crimson', holds: ['2 dark white', '5 wavy black', '4 dull crimson']},
{color: 'posh maroon', holds: ['4 plaid silver', '4 vibrant lime', '4 posh gray', '3 dull maroon']},
{color: 'dull green', holds: ['5 muted tan', '5 drab red']},
{color: 'clear maroon', holds: ['3 faded brown']},
{color: 'striped yellow', holds: ['4 faded lavender', '1 wavy coral', '5 clear maroon']},
{color: 'dull tomato', holds: ['2 shiny white', '2 light silver', '4 dotted chartreuse', '4 dark brown']},
{color: 'drab chartreuse', holds: ['3 dotted beige', '3 pale chartreuse', '2 muted fuchsia', '5 light crimson']},
{color: 'plaid purple', holds: ['3 drab yellow']},
{color: 'light plum', holds: ['1 dotted aqua', '2 dark white']},
{color: 'mirrored brown', holds: ['3 mirrored teal', '2 dull cyan']},
{color: 'mirrored crimson', holds: ['3 dull chartreuse', '2 dark silver', '5 bright cyan', '4 dark tomato']},
{color: 'dull gold', holds: ['4 muted salmon']},
{color: 'wavy olive', holds: ['3 mirrored brown', '5 clear indigo']},
{color: 'faded turquoise', holds: ['2 clear salmon', '2 mirrored gray', '1 dark lime']},
{color: 'bright indigo', holds: ['2 faded lavender', '1 shiny gray', '4 mirrored indigo']},
{color: 'pale teal', holds: ['3 dark violet', '5 shiny salmon']},
{color: 'plaid orange', holds: ['5 faded green', '5 pale magenta']},
{color: 'shiny crimson', holds: ['5 shiny green', '1 bright tomato', '3 vibrant lime', '3 clear purple']},
{color: 'muted indigo', holds: ['4 dim brown', '1 dotted beige']},
{color: 'dark cyan', holds: ['2 striped yellow']},
{color: 'dull teal', holds: ['1 muted indigo', '2 drab chartreuse', '5 faded beige']},
{color: 'striped fuchsia', holds: ['1 mirrored teal', '3 dull black', '2 dim salmon', '5 wavy salmon']},
{color: 'drab crimson', holds: ['5 dim teal', '2 wavy red', '3 dark brown']},
{color: 'dull olive', holds: ['1 clear yellow', '4 plaid indigo', '4 posh tomato', '1 dotted orange']},
{color: 'muted lime', holds: ['2 light white', '5 dotted violet', '5 posh gold', '2 bright cyan']},
{color: 'dark purple', holds: ['1 light lavender', '2 plaid olive', '5 striped maroon', '1 dotted gold']},
{color: 'dull yellow', holds: ['5 mirrored beige']},
{color: 'dotted maroon', holds: ['3 clear salmon', '1 light salmon']},
{color: 'dull beige', holds: ['5 shiny fuchsia']},
{color: 'clear green', holds: ['4 muted lavender', '5 faded orange', '4 faded silver', '4 clear red']},
{color: 'striped magenta', holds: ['2 dotted plum']},
{color: 'posh beige', holds: ['5 vibrant maroon', '1 dim lavender']},
{color: 'striped blue', holds: ['3 clear turquoise', '3 dark purple', '3 shiny yellow', '5 clear teal']},
{color: 'muted magenta', holds: ['3 striped orange', '5 dim brown']},
{color: 'vibrant orange', holds: ['1 bright teal', '1 drab salmon', '5 dull silver']},
{color: 'pale violet', holds: ['4 shiny tan', '2 clear turquoise', '2 pale salmon', '2 dotted aqua']},
{color: 'dotted aqua', holds: ['2 striped turquoise', '1 dim fuchsia', '2 pale chartreuse', '2 bright turquoise']},
{color: 'clear black', holds: ['4 dotted beige', '1 dull brown', '2 dull teal']},
{color: 'light tan', holds: ['3 dotted red', '1 dark red']},
{color: 'pale green', holds: ['4 dull salmon', '4 dim brown']},
{color: 'dim tan', holds: ['2 posh silver', '2 dark fuchsia']},
{color: 'plaid coral', holds: ['2 vibrant plum', '5 vibrant red', '3 dim salmon']},
{color: 'wavy lavender', holds: ['2 dark gold', '5 plaid blue', '1 dim yellow']},
{color: 'dim violet', holds: ['2 clear tan', '5 pale magenta']},
{color: 'dotted black', holds: ['4 dark magenta']},
{color: 'mirrored salmon', holds: ['3 vibrant beige', '3 vibrant purple']},
{color: 'dark green', holds: ['4 dotted yellow', '1 faded green', '3 muted lavender']},
{color: 'faded blue', holds: ['4 clear turquoise', '1 posh indigo', '2 faded green']},
{color: 'pale black', holds: ['2 pale coral', '3 faded black', '3 mirrored teal', '4 muted chartreuse']},
{color: 'plaid black', holds: ['3 posh brown', '3 dark maroon', '1 mirrored black']},
{color: 'dim olive', holds: ['5 posh indigo']},
{color: 'dark lavender', holds: ['3 light gold', '5 dim purple']},
{color: 'shiny turquoise', holds: ['3 dim fuchsia', '4 faded silver', '4 dim salmon']},
{color: 'light green', holds: ['1 drab red']},
{color: 'wavy plum', holds: ['2 wavy gold', '5 bright tan']},
{color: 'vibrant tan', holds: ['3 drab gray']},
{color: 'shiny orange', holds: ['2 clear plum', '1 posh red']},
{color: 'dull lime', holds: ['3 pale silver']},
{color: 'shiny cyan', holds: ['3 shiny purple']},
{color: 'posh brown', holds: ['1 striped salmon', '2 dotted beige']},
{color: 'mirrored blue', holds: ['2 muted olive', '5 mirrored aqua']},
{color: 'dark red', holds: ['2 shiny purple', '4 dim salmon', '2 wavy salmon']},
{color: 'wavy gray', holds: ['4 striped fuchsia', '2 wavy salmon', '4 faded silver']},
{color: 'clear gold', holds: ['2 vibrant plum']},
{color: 'dark silver', holds: ['4 striped gold', '4 plaid teal', '1 pale yellow']},
{color: 'dim cyan', holds: ['4 mirrored blue', '1 vibrant red', '5 shiny indigo', '5 muted gray']},
{color: 'bright chartreuse', holds: ['4 light yellow', '3 faded lavender']},
{color: 'dotted green', holds: ['3 pale indigo', '3 drab gray', '2 dark white', '4 light yellow']},
{color: 'vibrant bronze', holds: ['5 light white', '1 dim lime', '5 dim brown', '5 plaid coral']},
{color: 'muted purple', holds: ['3 dark maroon']},
{color: 'bright salmon', holds: ['3 clear beige']},
{color: 'mirrored lime', holds: ['1 wavy coral', '1 mirrored gray']},
{color: 'faded cyan', holds: ['2 pale bronze', '3 vibrant plum']},
{color: 'dull aqua', holds: ['2 dark coral', '3 clear turquoise']},
{color: 'posh aqua', holds: ['1 pale teal', '2 dim coral']},
{color: 'wavy aqua', holds: ['2 posh indigo', '4 shiny cyan', '3 muted tan']},
{color: 'dark magenta', holds: ['1 pale red', '1 dull brown', '3 faded lavender']},
{color: 'striped lavender', holds: ['4 striped gold', '3 mirrored olive', '2 dim lime', '1 muted indigo']},
{color: 'bright turquoise', holds: []},
{color: 'dim teal', holds: ['5 dark white', '2 faded chartreuse', '1 striped beige', '4 muted gold']},
{color: 'wavy yellow', holds: ['4 pale fuchsia']},
{color: 'muted black', holds: ['1 striped salmon', '1 shiny gold', '3 plaid gray']},
{color: 'dark beige', holds: ['3 wavy gray', '5 dim red']},
{color: 'mirrored tan', holds: ['2 faded purple', '4 faded lime', '5 dull lavender', '4 dark plum']},
{color: 'vibrant teal', holds: ['1 dark teal', '4 dotted chartreuse']},
{color: 'bright plum', holds: ['1 vibrant silver']},
{color: 'dotted purple', holds: ['3 faded beige', '3 muted lavender']},
{color: 'faded tomato', holds: ['1 muted olive', '5 faded orange', '5 light yellow']},
{color: 'light crimson', holds: []},
{color: 'drab fuchsia', holds: ['2 vibrant silver', '1 dim fuchsia', '3 clear plum', '1 drab gold']},
{color: 'muted blue', holds: ['1 dotted silver', '5 dull beige', '3 posh silver']},
{color: 'dark brown', holds: ['1 clear red', '2 light yellow', '1 wavy gold', '2 plaid olive']},
{color: 'dim gold', holds: ['4 dotted purple', '3 plaid blue']},
{color: 'dim crimson', holds: ['5 muted magenta']},
{color: 'shiny teal', holds: ['1 dotted bronze', '4 vibrant teal', '4 pale blue']},
{color: 'drab blue', holds: ['3 dark salmon']},
{color: 'bright olive', holds: ['5 pale fuchsia']},
{color: 'mirrored gold', holds: ['2 posh brown', '2 bright purple', '5 shiny cyan']},
{color: 'dim turquoise', holds: ['4 pale cyan', '2 mirrored violet']},
{color: 'clear silver', holds: ['4 dark plum', '4 pale gray', '5 mirrored bronze']},
{color: 'clear olive', holds: ['4 muted green']},
{color: 'drab lime', holds: ['3 dotted aqua', '2 faded blue', '3 faded salmon', '3 dim yellow']},
{color: 'dim fuchsia', holds: []},
{color: 'mirrored black', holds: ['1 dark white']},
{color: 'clear cyan', holds: ['3 plaid chartreuse', '3 plaid teal', '5 dark gold', '5 dim lime']},
{color: 'bright tomato', holds: ['4 dark green']},
{color: 'dim white', holds: ['2 shiny yellow', '1 pale maroon']},
{color: 'light turquoise', holds: ['5 posh blue', '2 light fuchsia']},
{color: 'shiny olive', holds: ['5 vibrant white', '3 dark salmon', '5 dotted tan']},
{color: 'striped maroon', holds: ['1 mirrored olive']},
{color: 'striped salmon', holds: ['3 muted indigo', '5 wavy salmon', '4 shiny maroon', '4 dim fuchsia']},
{color: 'striped orange', holds: ['2 dotted purple', '4 shiny cyan', '1 drab gold', '4 dark beige']},
{color: 'posh olive', holds: ['3 faded tomato', '5 posh blue', '1 clear red']},
{color: 'shiny plum', holds: ['3 pale purple', '3 dim beige']},
{color: 'dark olive', holds: ['4 dull coral']},
{color: 'dotted teal', holds: ['5 plaid lavender', '4 clear bronze', '4 dim lime', '3 pale maroon']},
{color: 'clear brown', holds: ['2 wavy teal', '1 faded green', '5 light white']},
{color: 'clear crimson', holds: ['4 pale turquoise', '5 plaid green', '3 shiny aqua', '5 wavy turquoise']},
{color: 'mirrored maroon', holds: ['5 bright coral', '5 drab orange']},
{color: 'wavy violet', holds: ['4 mirrored tomato', '4 striped gold']},
{color: 'plaid olive', holds: ['3 dotted silver']},
{color: 'light purple', holds: ['2 dark red', '5 dull cyan', '4 plaid black']},
{color: 'wavy orange', holds: ['1 dim green', '4 dark coral']},
{color: 'vibrant red', holds: ['4 posh brown']},
{color: 'wavy silver', holds: ['5 faded orange', '2 wavy coral', '4 faded silver']},
{color: 'dark tan', holds: ['3 mirrored brown', '2 bright plum', '2 plaid silver']},
{color: 'vibrant blue', holds: ['1 wavy salmon', '5 pale green']},
{color: 'shiny bronze', holds: ['5 wavy white', '1 dim indigo', '5 muted crimson', '5 shiny lime']},
{color: 'clear red', holds: ['1 dotted aqua', '3 pale chartreuse', '2 muted teal', '5 posh brown']},
{color: 'dotted silver', holds: ['2 dark maroon', '3 dim brown']},
{color: 'bright tan', holds: ['1 posh black', '5 striped orange', '5 drab gold']},
{color: 'drab red', holds: ['5 posh gray']},
{color: 'striped purple', holds: ['1 striped silver', '1 pale blue', '4 mirrored black']},
{color: 'striped bronze', holds: ['2 striped gold', '5 light crimson', '5 faded tomato', '3 wavy indigo']},
{color: 'pale red', holds: ['2 mirrored olive', '5 faded orange', '4 faded chartreuse', '2 plaid chartreuse']},
{color: 'dim plum', holds: ['4 vibrant coral', '3 clear purple', '3 dull blue']},
{color: 'muted yellow', holds: ['2 clear red', '3 pale plum']},
{color: 'posh salmon', holds: ['3 pale tan', '3 wavy gold']},
{color: 'mirrored bronze', holds: ['4 faded bronze', '1 clear black', '5 dark white']},
{color: 'muted cyan', holds: ['2 dim plum']},
{color: 'vibrant fuchsia', holds: ['1 faded teal', '2 muted teal', '3 pale chartreuse', '3 bright teal']},
{color: 'mirrored fuchsia', holds: ['4 dull red', '1 light cyan', '3 wavy crimson', '3 wavy yellow']},
{color: 'clear indigo', holds: ['5 clear bronze', '4 dark coral', '4 drab chartreuse']},
{color: 'pale bronze', holds: ['2 faded salmon', '1 shiny black', '3 pale yellow', '3 dotted chartreuse']},
{color: 'pale purple', holds: ['4 mirrored black', '1 vibrant silver', '2 striped beige', '5 dotted chartreuse']},
{color: 'muted gray', holds: ['4 shiny purple', '4 light green', '1 pale fuchsia']},
{color: 'clear blue', holds: ['5 dotted olive', '4 light purple']},
{color: 'posh cyan', holds: ['5 muted tan', '1 dotted cyan', '4 wavy gold']},
{color: 'bright purple', holds: ['4 wavy salmon', '1 dark teal', '4 pale yellow']},
{color: 'drab aqua', holds: ['1 vibrant red']},
{color: 'pale silver', holds: ['4 light lavender', '2 mirrored bronze', '1 striped teal']},
{color: 'dark blue', holds: ['3 dull beige', '4 faded salmon', '1 dull black', '5 posh salmon']},
{color: 'plaid tan', holds: ['1 plaid lavender', '5 pale lavender', '4 light aqua']},
{color: 'posh tan', holds: ['3 dotted lime']},
{color: 'drab maroon', holds: ['5 mirrored chartreuse']},
{color: 'dim magenta', holds: ['1 pale fuchsia', '2 light fuchsia', '5 bright bronze', '1 faded gray']},
{color: 'shiny purple', holds: ['2 pale chartreuse']},
{color: 'drab turquoise', holds: ['4 light turquoise']},
{color: 'light bronze', holds: ['2 posh black', '3 dark yellow', '3 faded plum']},
{color: 'plaid gold', holds: ['4 dark teal', '4 shiny plum']},
{color: 'dim maroon', holds: ['2 clear plum', '3 striped aqua', '2 striped teal']},
{color: 'drab coral', holds: ['3 faded chartreuse', '2 drab plum', '3 faded red', '1 dark blue']},
{color: 'faded gray', holds: ['3 pale gray', '2 dull beige', '5 wavy indigo']},
{color: 'dotted magenta', holds: ['2 light salmon']},
{color: 'light magenta', holds: ['3 posh yellow', '3 dotted green', '1 drab violet']},
{color: 'dotted cyan', holds: ['2 faded plum']},
{color: 'dim orange', holds: ['5 light brown', '5 bright yellow']},
{color: 'posh teal', holds: ['1 faded beige', '5 mirrored gold', '5 bright teal']},
{color: 'dim purple', holds: ['2 light silver', '5 muted red', '1 mirrored gold', '2 posh orange']},
{color: 'shiny tomato', holds: ['3 striped coral', '3 dark plum', '5 plaid turquoise']},
{color: 'vibrant olive', holds: ['3 vibrant lime', '5 mirrored white', '1 pale bronze', '2 striped cyan']},
{color: 'dull lavender', holds: ['5 muted gold', '5 pale maroon']},
{color: 'light black', holds: ['1 dark plum', '1 shiny gold']},
{color: 'bright magenta', holds: ['3 striped turquoise', '3 dim gray']},
{color: 'drab tomato', holds: ['3 vibrant purple', '4 shiny purple', '2 light maroon']},
{color: 'posh turquoise', holds: ['2 bright aqua', '2 striped salmon', '5 muted green']},
{color: 'dotted yellow', holds: ['3 dark red', '3 wavy gold']},
{color: 'plaid lavender', holds: ['4 striped turquoise', '1 dotted olive', '1 clear green', '4 shiny beige']},
{color: 'drab black', holds: ['5 dotted magenta', '2 drab yellow', '2 striped turquoise', '1 dark bronze']},
{color: 'clear beige', holds: ['4 striped salmon']},
{color: 'light lavender', holds: ['1 wavy silver', '1 dark indigo']},
{color: 'posh red', holds: ['4 muted olive', '3 light tan', '4 clear gray', '2 dim lime']},
{color: 'clear coral', holds: ['3 light lime', '2 posh violet']},
{color: 'plaid salmon', holds: ['2 pale yellow', '5 dark plum']},
{color: 'pale gold', holds: ['2 striped teal', '3 faded crimson']},
{color: 'wavy red', holds: ['4 faded green', '5 dim coral', '4 wavy silver', '4 plaid brown']},
{color: 'faded white', holds: ['2 posh tomato', '1 posh green', '4 vibrant lavender']},
{color: 'dull indigo', holds: ['3 muted olive', '4 shiny purple', '3 drab chartreuse', '1 dotted orange']},
{color: 'wavy green', holds: ['3 pale indigo', '1 striped purple', '5 dotted coral', '1 shiny tan']},
{color: 'shiny red', holds: ['4 pale fuchsia', '2 posh salmon']},
{color: 'vibrant cyan', holds: ['1 faded salmon', '1 faded black', '4 striped coral']},
{color: 'dark tomato', holds: ['3 clear maroon', '4 plaid maroon', '5 dotted aqua']},
{color: 'vibrant gold', holds: ['1 shiny fuchsia']},
{color: 'dark black', holds: ['2 wavy lime', '1 pale cyan', '4 posh brown']},
{color: 'posh fuchsia', holds: ['4 pale purple', '2 dull lavender']},
{color: 'light silver', holds: ['2 vibrant plum', '2 pale magenta', '4 pale chartreuse', '3 plaid chartreuse']},
{color: 'dark yellow', holds: ['1 dotted crimson', '3 faded orange', '5 posh teal', '1 clear plum']},
{color: 'mirrored turquoise', holds: ['2 muted teal']},
{color: 'drab purple', holds: ['5 dotted plum', '1 plaid plum']},
{color: 'dotted tan', holds: ['1 pale plum', '1 dotted aqua']},
{color: 'drab bronze', holds: ['4 vibrant red', '4 light blue']},
{color: 'mirrored cyan', holds: ['1 dark white', '4 dark lime', '5 vibrant silver']},
{color: 'shiny aqua', holds: ['5 wavy plum', '4 drab maroon', '2 drab chartreuse']},
{color: 'striped aqua', holds: ['1 plaid blue', '1 dark plum', '4 faded lavender']},
{color: 'dotted plum', holds: ['5 mirrored green', '1 dark plum', '4 dark maroon']},
{color: 'faded gold', holds: ['4 pale yellow']},
{color: 'vibrant beige', holds: ['2 light lavender', '3 faded indigo']},
{color: 'light brown', holds: []}
];

module.exports = puzzleInput;